@baseUrl = http://localhost:3000
@token =

###
# Сервер працює
GET {{baseUrl}}/

###
# ЛР9. Реєстрація користувача
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "name": "Ivan Petrenko",
  "email": "ivan@example.com",
  "password": "password123",
  "confirmPassword": "password123"
}

###
# ЛР10. Успішний вхід
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "ivan@example.com",
  "password": "password123"
}

###
# ЛР10. Невірний пароль
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "ivan@example.com",
  "password": "wrongpassword"
}

###
# ЛР10. Профіль з токеном
GET {{baseUrl}}/api/auth/me
Authorization: Bearer {{token}}

###
# ЛР10. Профіль без токена
GET {{baseUrl}}/api/auth/me

###
# ЛР10. Профіль з невірним токеном
GET {{baseUrl}}/api/auth/me
Authorization: Bearer wrong.token.value
