@baseUrl = http://localhost:3000

###
# Сервер і клієнт
GET {{baseUrl}}/

###
# Сторінка реєстрації
GET {{baseUrl}}/register.html

###
# Сторінка входу
GET {{baseUrl}}/login.html

###
# Головна сторінка зі списком товарів
GET {{baseUrl}}/index.html

###
# Форма створення товару
GET {{baseUrl}}/create.html
